const first = (n) => console.log('first',n)
const second = (n) => console.log('second',n)
const third = (n) => console.log('third',n)
first(1)
second(2)
third(3)
setTimeout(first,0)
second(5)
third(6)
setTimeout(second,1)
setTimeout(first,0)
third(9)
